// <auto-generated />
using AiDevRequest.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AiDevRequest.API.Data.Migrations;

[DbContext(typeof(AiDevRequestDbContext))]
[Migration("20260215000000_AddProjectTemplatesTable")]
partial class AddProjectTemplatesTable
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Minimal target model — full snapshot is in AiDevRequestDbContextModelSnapshot.cs
    }
}
